### ISSUE TITLE
Build fails on win10

### ISSUE THREAD

**Issue by acaceres2176** [HyperionGray/hg-winafl#7]
PS C:\Users\Garrett McParrot\Desktop\fuzzers\hg-winafl> pwd

Path
----
C:\Users\Garrett McParrot\Desktop\fuzzers\hg-winafl

PS C:\Users\Garrett McParrot\Desktop\fuzzers\hg-winafl> python .\helper.py
Usage: .\helper.py build | generate | help | run
PS C:\Users\Garrett McParrot\Desktop\fuzzers\hg-winafl> python .\helper.py build
vcvarsall.bat x86 && cd C:\Users\Garrett McParrot\Desktop\fuzzers\hg-winafl\winafl\bin32 && cmake -G"Visual Studio 15 2017" .. -DDynamoRIO_DIR=C:\Users\Garrett McParrot\Desktop\fuzzers\hg-winafl\winafl\dynamrio\cmake && cmake --build C:\Users\Garrett McParrot\Desktop\fuzzers\hg-winafl\winafl\bin32 --config Release
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.7.6
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'
CMake Error: The source directory "C:/Users/Garrett McParrot/Desktop/fuzzers/hg-winafl/winafl/bin32/McParrot/Desktop/fuzzers/hg-winafl/winafl/dynamrio/cmake" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
vcvarsall.bat x64 && cd C:\Users\Garrett McParrot\Desktop\fuzzers\hg-winafl\winafl\bin64 && cmake -G"Visual Studio 15 2017 Win64" .. -DDynamoRIO_DIR=C:\Users\Garrett McParrot\Desktop\fuzzers\hg-winafl\winafl\dynamrio\cmake && cmake --build C:\Users\Garrett McParrot\Desktop\fuzzers\hg-winafl\winafl\bin64 --config Release
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.7.6
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
CMake Error: The source directory "C:/Users/Garrett McParrot/Desktop/fuzzers/hg-winafl/winafl/bin64/McParrot/Desktop/fuzzers/hg-winafl/winafl/dynamrio/cmake" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
PS C:\Users\Garrett McParrot\Desktop\fuzzers\hg-winafl> ls

**Comment by medioxor** [comment]
fixed build now works with spaces in name
